"""initial schema

Revision ID: ed674da17fbc
Revises:
Create Date: 2026-08-31 12:10:05.035077
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ed674da17fbc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analyses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("analysis_id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_name", sa.String(length=255), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("column_count", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column(
            "score_breakdown",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("app_version", sa.String(length=32), nullable=False),
        sa.Column("rule_set_name", sa.String(length=120), nullable=True),
        sa.Column(
            "notes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("analyses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_analyses_analysis_id"), ["analysis_id"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_analyses_content_hash"), ["content_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_analyses_created_at"), ["created_at"], unique=False)

    op.create_table(
        "ai_calls",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("analysis_pk", sa.Integer(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("task", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("error_type", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(["analysis_pk"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_calls", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_calls_analysis_pk"), ["analysis_pk"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_calls_task"), ["task"], unique=False)

    op.create_table(
        "analysis_columns",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("analysis_pk", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("pandas_dtype", sa.String(length=64), nullable=False),
        sa.Column("semantic_type", sa.String(length=32), nullable=False),
        sa.Column("semantic_type_confidence", sa.Float(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("missing_count", sa.Integer(), nullable=False),
        sa.Column("unique_count", sa.Integer(), nullable=False),
        sa.Column("column_score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["analysis_pk"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("analysis_columns", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_analysis_columns_analysis_pk"), ["analysis_pk"], unique=False
        )

    op.create_table(
        "applied_changes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("analysis_pk", sa.Integer(), nullable=False),
        sa.Column("proposal_id", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("column_name", sa.String(length=255), nullable=True),
        sa.Column("rows_changed", sa.Integer(), nullable=False),
        sa.Column(
            "parameters",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["analysis_pk"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("applied_changes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_applied_changes_analysis_pk"), ["analysis_pk"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_applied_changes_proposal_id"), ["proposal_id"], unique=False
        )

    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("analysis_pk", sa.Integer(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["analysis_pk"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_events_analysis_pk"), ["analysis_pk"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_events_occurred_at"), ["occurred_at"], unique=False
        )

    op.create_table(
        "correction_proposals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("analysis_pk", sa.Integer(), nullable=False),
        sa.Column("proposal_id", sa.String(length=32), nullable=False),
        sa.Column("finding_id", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("column_name", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "parameters",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("affected_rows", sa.Integer(), nullable=False),
        sa.Column("destructive", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("decision_status", sa.String(length=16), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.String(length=120), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["analysis_pk"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("correction_proposals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_correction_proposals_action"), ["action"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_correction_proposals_analysis_pk"), ["analysis_pk"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_correction_proposals_decision_status"), ["decision_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_correction_proposals_finding_id"), ["finding_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_correction_proposals_proposal_id"), ["proposal_id"], unique=False
        )

    op.create_table(
        "findings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("analysis_pk", sa.Integer(), nullable=False),
        sa.Column("finding_id", sa.String(length=32), nullable=False),
        sa.Column("check_id", sa.String(length=64), nullable=False),
        sa.Column("issue_type", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("column_name", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("affected_rows", sa.Integer(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["analysis_pk"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_findings_analysis_pk"), ["analysis_pk"], unique=False)
        batch_op.create_index(
            "ix_findings_analysis_severity", ["analysis_pk", "severity"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_findings_check_id"), ["check_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_findings_finding_id"), ["finding_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_findings_issue_type"), ["issue_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_findings_severity"), ["severity"], unique=False)
        batch_op.create_index(batch_op.f("ix_findings_source"), ["source"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_findings_source"))
        batch_op.drop_index(batch_op.f("ix_findings_severity"))
        batch_op.drop_index(batch_op.f("ix_findings_issue_type"))
        batch_op.drop_index(batch_op.f("ix_findings_finding_id"))
        batch_op.drop_index(batch_op.f("ix_findings_check_id"))
        batch_op.drop_index("ix_findings_analysis_severity")
        batch_op.drop_index(batch_op.f("ix_findings_analysis_pk"))

    op.drop_table("findings")
    with op.batch_alter_table("correction_proposals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_correction_proposals_proposal_id"))
        batch_op.drop_index(batch_op.f("ix_correction_proposals_finding_id"))
        batch_op.drop_index(batch_op.f("ix_correction_proposals_decision_status"))
        batch_op.drop_index(batch_op.f("ix_correction_proposals_analysis_pk"))
        batch_op.drop_index(batch_op.f("ix_correction_proposals_action"))

    op.drop_table("correction_proposals")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_audit_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_audit_events_analysis_pk"))

    op.drop_table("audit_events")
    with op.batch_alter_table("applied_changes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_applied_changes_proposal_id"))
        batch_op.drop_index(batch_op.f("ix_applied_changes_analysis_pk"))

    op.drop_table("applied_changes")
    with op.batch_alter_table("analysis_columns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analysis_columns_analysis_pk"))

    op.drop_table("analysis_columns")
    with op.batch_alter_table("ai_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_calls_task"))
        batch_op.drop_index(batch_op.f("ix_ai_calls_analysis_pk"))

    op.drop_table("ai_calls")
    with op.batch_alter_table("analyses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analyses_created_at"))
        batch_op.drop_index(batch_op.f("ix_analyses_content_hash"))
        batch_op.drop_index(batch_op.f("ix_analyses_analysis_id"))

    op.drop_table("analyses")
    # ### end Alembic commands ###
