"""Database access: SQLAlchemy models, sessions and the repository layer."""

from dqcopilot.db.models import (
    AiCallRecord,
    Analysis,
    AnalysisColumn,
    AppliedChangeRecord,
    AuditEvent,
    Base,
    FindingRecord,
    ProposalRecord,
)
from dqcopilot.db.repository import (
    ai_usage_totals,
    approved_changes,
    audit_trail,
    content_hash,
    find_analysis,
    log_event,
    recent_analyses,
    record_ai_call,
    redact_details,
    require_analysis,
    save_analysis,
    save_cleaned_dataset,
    save_review,
)
from dqcopilot.db.session import (
    DatabaseUnavailableError,
    build_engine,
    check_connection,
    create_all,
    ensure_schema,
    get_engine,
    get_session_factory,
    reset_caches,
    session_scope,
)

__all__ = [
    "AiCallRecord",
    "Analysis",
    "AnalysisColumn",
    "AppliedChangeRecord",
    "AuditEvent",
    "Base",
    "DatabaseUnavailableError",
    "FindingRecord",
    "ProposalRecord",
    "ai_usage_totals",
    "approved_changes",
    "audit_trail",
    "build_engine",
    "check_connection",
    "content_hash",
    "create_all",
    "ensure_schema",
    "find_analysis",
    "get_engine",
    "get_session_factory",
    "log_event",
    "recent_analyses",
    "record_ai_call",
    "redact_details",
    "require_analysis",
    "reset_caches",
    "save_analysis",
    "save_cleaned_dataset",
    "save_review",
    "session_scope",
]
